#! /usr/bin/env dash

export SXHKD_SHELL='/bin/dash'

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output DisplayPort-0 --primary --mode 1920x1080 --pos 1080x0 --rotate normal --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-0 --mode 1920x1080 --pos 0x0 --rotate left --output DVI-D-0 --off &
~/.config/polybar/launch.sh &
feh --bg-fill ~/backgrounds/pacman.jpg &
picom --config ~/.config/picom/picom.conf &

bspc monitor DisplayPort-0 -d code web music games misc
bspc monitor HDMI-A-0 -d discord

bspc config border_width 1
bspc config window_gap 15

bspc config split_ratio 0.65

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Firefox desktop='web' follow=on
bspc rule -a Chrome desktop='web' follow=on
bspc rule -a Chromium desktop='web' follow=on
bspc rule -a Code desktop='code' follow=on
bspc rule -a URxvt desktop='code' follow=on
bspc rule -a Discord desktop='discord' follow=on
bspc rule -a Keybase desktop='misc' follow=on

bspc config normal_border_color "#4952ca"
bspc config active_border_color "#4952ca"
bspc config focused_border_color "#4952ca"
bspc config presel_feedback_color "#4952ca"

bspc wm --reorder-monitors DisplayPort-0 HDMI-A-0 
