#! /usr/bin/env dash

#########################
# EXPORTS               #
#########################

export SXHKD_SHELL='/bin/dash'

#########################
# STARTUP               #
#########################

#
# For Dunst, `/usr/share/dbus-1/services/org.freedesktop.Notifications`
# Exec from ` /usr/lib/x86_64-linux-gnu/notify-osd` to `/usr/bin/dunst`

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output DisplayPort-0 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-0 --mode 1920x1080 --pos 0x0 --rotate normal --output DVI-D-0 --off &
~/.config/polybar/launch.sh &
killall -q dunst && dunst --config ~/.config/dunst/dunstrc &
feh --bg-fill ~/backgrounds/anime_crossover.png &
picom --config ~/.config/picom/picom.conf &
wmname LG3D &

#########################
# CONFIG                #
#########################

bspc monitor DisplayPort-0 -d dev www mus gfx chat tmp
bspc monitor HDMI-A-0 -d misc

bspc config border_width 0 
bspc config window_gap 10

bspc config split_ratio 0.65

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Firefox desktop='www' follow=on
bspc rule -a Chrome desktop='www' follow=on
bspc rule -a Chromium desktop='www' follow=on
bspc rule -a Code desktop='dev' follow=on
bspc rule -a URxvt desktop='dev' follow=on
bspc rule -a Discord desktop='chat' follow=on
bspc rule -a Keybase desktop='chat' follow=on

bspc config normal_border_color "#444444"
bspc config active_border_color "#444444"
bspc config focused_border_color "#444444"
bspc config presel_feedback_color "#444444"

bspc wm --reorder-monitors DisplayPort-0 HDMI-A-0 
